apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patchesStrategicMerge:
  - secret.yaml
  - backend-patch.yaml
  - frontend-patch.yaml
  - batabase-patch.yaml
